 const ActionTypes = {

 	// Markers
 	FETCH_MARKERS: "FETCH_MARKERS",
 	ADD_MARKERS: "ADD_MARKERS",
 	CLEAR_MARKERS: "CLEAR_MARKERS",
 	FETCH_MARKERS_ERROR: "FETCH_MARKERS_ERROR",

 	// Location
 	FETCH_LOCATION: "FETCH_LOCATION",
 	FETCH_LOCATION_COMPLETE: "FETCH_LOCATION_COMPLETE",
 	FETCH_LOCATION_ERROR: "FETCH_LOCATION_ERROR"
 }

 export default ActionTypes